#!/bin/bash
echo "Digite o nome de um arquivo:"
read RESPOSTA
if test ["$RESPOSTA" -d]
then echo "Isso é um diretório." && exit 
elif test ["$RESPOSTA" -f] 
then echo "Isso é um arquivo normal." && exit 
else echo "Esse arquivo não existe."
